creating a class employee then adding a variable to count no of employees ,
creating a special method called constuctor within a class to initialize the variables within the class.
defining name family salary and department and incrementing the count of employees.
defining a method called average salary  which is used to return the average salary by using the formula total salary by no.of employees.

Class definition is required, but no attributes or methods yet is required in this class

defining employees and full time employees
 and calculating total salary and average salary
 printing the final results.


In [3]:
class Employee:
    no_Of_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.no_Of_employees += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.no_Of_employees

class FulltimeEmployee(Employee):
    pass

employee1 = Employee("madhu sravani", "Bolisetti", 90000, "IT")
employee2 = Employee("Durga Devi", "Bolisetti", 95000, "Finance")

fulltime_employee1 = FulltimeEmployee("Meghna", "reddy", 65000, "HR")
fulltime_employee2 = FulltimeEmployee("Sagar", "Manu", 50000, "QA")

total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)

Average Salary for Employees: 46250.0
Average Salary for Fulltime Employees: 28750.0


imporing numpy which is a fundamental package
generating random vector from 1 to 20 with size 20
printing it

In [5]:

import numpy as np
randomized_Vector = np.random.uniform(1, 20, 20)
print("Original Random Vector:\n", randomized_Vector)

Original Random Vector:
 [12.58309606 13.29995453  1.35935663 12.2485254  10.15827944  1.90568021
 19.32412575 16.47235263  5.87591209 11.55041617  3.73156452 12.84125991
 17.23622688  8.23880107  8.55777524  3.11999275  4.13691014 16.24526086
  9.5517482   8.46147643]


reshaping the randomly generated vector using inbuilt function called reshape which helps in reshping the array to 4 rows and 5 columns
printing the output

In [6]:
reshaped_array = randomized_Vector.reshape(4, 5)
print(reshaped_array)

[[12.58309606 13.29995453  1.35935663 12.2485254  10.15827944]
 [ 1.90568021 19.32412575 16.47235263  5.87591209 11.55041617]
 [ 3.73156452 12.84125991 17.23622688  8.23880107  8.55777524]
 [ 3.11999275  4.13691014 16.24526086  9.5517482   8.46147643]]


arranging the array and changing the max element in each row to zero using argmax function.

In [7]:

reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[12.58309606  0.          1.35935663 12.2485254  10.15827944]
 [ 1.90568021  0.         16.47235263  5.87591209 11.55041617]
 [ 3.73156452 12.84125991  0.          8.23880107  8.55777524]
 [ 3.11999275  4.13691014  0.          9.5517482   8.46147643]]
